const PageBlock = {
  MODE_PAGE: 1,
  MODE_TEMPLATE: 3,

  TYPE_TEXT: 1,
  TYPE_TEXT_WITH_IMAGE: 3,
  TYPE_TEXT_GRID: 5,
  TYPE_BANNER: 7,
  TYPE_PRODUCT: 9,
  TYPE_CAROUSEL: 11,
  TYPE_FORM: 13,
  TYPE_INLINE_HTML: 15,
  TYPE_INLINE_JAVASCRIPT: 17,
  TYPE_LIST: 19,
};

export default PageBlock;
