const ProductFilter = {
  TYPE_CATEGORY: 1,
  TYPE_ATTRIBUTE: 3,
  TYPE_COLOR: 5,
  TYPE_SIZE: 7,
  TYPE_TAGS: 9,
  TYPE_PRICE: 11,
  TYPE_RATING: 13,
  TYPE_INSTOCK: 15,
  TYPE_ONSALE: 17,
  TYPE_BRAND: 19,

  STYLE_CHECKBOX: 1,
  STYLE_RADIO_BUTTON: 3,
  STYLE_TEXT: 5,
  STYLE_IMAGE: 7,
  STYLE_IMAGE_AND_TEXT: 9,
  STYLE_RANGE_SLIDER: 11,
};

export default ProductFilter;
