const ProductVariant = {
  STATUS_DRAFT: 1,
  STATUS_ACTIVE: 3,
  STATUS_ARCHIVED: 5,
  STATUS_OUT_OF_STOCK: 7,

  VISIBILITY_CATALOG: 1,
  VISIBILITY_SEARCH: 3,

  INSTALLMENT_ENABLED: 1,
  INSTALLMENT_ALLOW_ZERO_RATE: 3,
  INSTALLMENT_ALLOW_PREORDER: 5,
  INSTALLMENT_COMING_SOON: 7,

  PAYMENT_ONLINE_IS_ALLOWED: 1,
  PAYMENT_INSTALLMENT_ONLINE_IS_ALLOWED: 3,

  COMBO_VARIANT_EXCHANGE_MODE_DENY: 1,
  COMBO_VARIANT_EXCHANGE_MODE_ALLOW_ALL: 3,
  COMBO_VARIANT_EXCHANGE_MODE_ALLOW_IN_LIST: 5,
};

export default ProductVariant;
