const Product = {
  STATUS_DRAFT: 1,
  STATUS_ACTIVE: 3,
  STATUS_ARCHIVED: 5,
  STATUS_OUT_OF_STOCK: 7,

  TYPE_GOODS_NORMAL: 1,
  TYPE_GOODS_IMEI: 3,
  TYPE_GOODS_COMBO: 5,
  TYPE_SERVICE: 7,

  VISIBILITY_CATALOG: 1,
  VISIBILITY_SEARCH: 3,

  INSTALLMENT_ENABLED: 1,
  INSTALLMENT_ALLOW_ZERO_RATE: 3,
  INSTALLMENT_ALLOW_PREORDER: 5,
  INSTALLMENT_COMING_SOON: 7,

  PAYMENT_ONLINE_IS_ALLOWED: 1,
  PAYMENT_INSTALLMENT_ONLINE_IS_ALLOWED: 3,

  TYPE_AVATAR: 1,
  TYPE_PHOTO: 3,
  TYPE_PHOTO_360: 5,
  TYPE_YOUTUBE: 7,
  TYPE_STICKER_TOP_LEFT: 9,
  TYPE_STICKER_TOP_RIGHT: 11,
  TYPE_STICKER_BOTTOM_LEFT: 13,
  TYPE_STICKER_BOTTOM_RIGHT: 15,

  UNIT_DEFAULT: 1,
  UNIT_BAG: 3,
  UNIT_CARTON: 5,
  UNIT_TICKET: 7,
  UNIT_BOTTLE: 9,
  UNIT_PIECE: 11,
  UNIT_GLASS: 13,
  UNIT_ANIMAL: 15,
  UNIT_SET: 17,
  UNIT_PAIR: 19,
  UNIT_ROLL: 21,
  UNIT_BOOK: 23,

  UNIT_GRAM: 25,
  UNIT_KILOGRAM: 27,
  UNIT_MILLILITER: 29,
  UNIT_LITER: 31,
  UNIT_MILLIMETER: 33,
  UNIT_CENTIMETER: 35,
  UNIT_DECIMETER: 37,
  UNIT_METER: 39,
  UNIT_KILOMETER: 41,
  UNIT_SQUAREMETER: 43,
  UNIT_SQUAREKILOMETER: 45,

  SORTER_DEFAULT: 1,
  SORTER_PRICE_INCREASE: 3,
  SORTER_PRICE_DECREASE: 5,
  SORTER_DISCOUNT_PERCENT_DECREASE: 7,
};

export default Product;
